<?php


class cobruPaymentModuleFrontController extends ModuleFrontController
{
    public $ssl = true;

    public  $display_column_left = false;

    public $display_column_right = false;

    public $template = '';

    public  $cobru;

    public function __construct()
    {
        parent::__construct();
        $this->cobru = new cobru();
    }

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub
    }

    public function postProcess()
    {
        $this->setTemplate('module:cobru/views/templates/front/payment.tpl');

        if(!$this->cobru->active || !array_key_exists('HTTP_X_FORWARDED_FOR', $_SERVER)) {
            return;
        }

        $allowedIpList = [CobruService::DEVELOMENT_IP, CobruService::PRODUCTION_IP];

        if (!in_array($_SERVER['HTTP_X_FORWARDED_FOR'], $allowedIpList)) {
            return;
        }

        $data = file_get_contents('php://input');

        if(!$data) {
            return;
        }

        $data = json_decode($data, true);

        if(!array_key_exists('state', $data)) {
            return;
        }

        if($data['state'] != cobru::SUCCESS_PAYMENT_STATUS) {
            return;
        }

       $this->cobru->successPaymentCobru($data);

    }

}